### ISSUE TITLE
Error: No file found matching path: /__hmr_update

### ISSUE THREAD

**Issue by migueloop** [lyphtec/markdown-serve#10]
Hi, I´m integrating [react-pwa](https://github.com/Atyantik/react-pwa) with this library but I´m getting this error.

```
Error: No file found matching path: /__hmr_update
    at MarkdownServer.get (/Users/migueloop/dev/rt_pwa/node_modules/markdown-serve/lib/server.js:294:25)
    at /Users/migueloop/dev/rt_pwa/node_modules/markdown-serve/lib/server.js:181:20
    at Layer.handle [as handle_request] (/Users/migueloop/dev/rt_pwa/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/migueloop/dev/rt_pwa/node_modules/express/lib/router/index.js:317:13)
    at /Users/migueloop/dev/rt_pwa/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/migueloop/dev/rt_pwa/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/migueloop/dev/rt_pwa/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/migueloop/dev/rt_pwa/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/migueloop/dev/rt_pwa/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/migueloop/dev/rt_pwa/node_modules/express/lib/router/index.js:317:13)
 ｢wdm｣: wait until bundle finished: /__hmr_update
```

I think It's something related with webpack.

I added an if condition in line 180 of server.js file to avoid this error as a workaround. Any idea?

**Comment by lyphtec** [comment]
Hi,

Not sure.  Are you able provide a sample project with this issue so I can investigate?

**Comment by migueloop** [comment]
Absolutely!

https://github.com/migueloop/rt_pwa/tree/dev

Thanks so much lyphtec
